name: native_test_job_definition
description: Launches qemu tests
inputs:
  make_check_args:
    description: Make arguments for extra check runs such as 'check-unit'
    required: true 
    default: check
runs:
  script:
    - run: scripts/git-submodule.sh update
        $(sed -n '/GIT_SUBMODULES=/ s/.*=// p' build/config-host.mak)
    - run: cd build
    - run: find . -type f -exec touch {} +
    # Avoid recompiling by hiding ninja with NINJA=":"
    - name: Launch check tests
      env: 
        MAKE_CHECK_ARGS: ${{ inputs.make_check_args }}
      run: make NINJA=":" $MAKE_CHECK_ARGS

