# @authors: Somya Arora, Arash Pourhabibi 
language: c
# We get submodules ourselves
git:
  submodules: false
dist: trusty
python:
  - "2.4"
sudo: required
matrix:
  include:
    - env:
      - TARGETS=aarch64-softmmu
      - FLEXUS="--enable-flexus --disable-tpm"
    - env:
      - TARGETS=sparc64-softmmu
      - FLEXUS="--enable-flexus --disable-tpm"
    - env:
      - TARGETS=aarch64-softmmu
      - FLEXUS=""
    - env:
      - TARGETS=sparc64-softmmu
      - FLEXUS=""
before_install:
  # Get GCC-4.8
  - sudo apt-get update -qq
  - sudo apt-get install -y python-software-properties
  - sudo apt-get install -y software-properties-common
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -y install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
install:
  # Get submodules
  - git submodule update --init --recursive
  - sudo apt-get update -qq
# Build Qemu  
before_script:
  - ./configure --target-list=${TARGETS} --disable-werror ${FLEXUS}
script:
  - make -j