name: Build and check tests brought by QEMU

on: 
  push:
    branches:
      - master
      - dev
      - dev-migrate-github-actions
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  native_build_job_definition:
    runs-on: ubuntu-latest
    name: native_build_job_definition
    strategy:
      matrix:
        include:
          - build-name: build-system-ubuntu
            targets: aarch64-softmmu
            configure-args: --enable-docs --enable-fdt=system --enable-slirp=system
            make-check-args: check-build
    env: 
      TARGETS: ${{ matrix.targets }}
      CONFIGURE_ARGS: ${{ matrix.configure-args }}
      MAKE_CHECK_ARGS: ${{ matrix.make-check-args }}
    steps:
# Figure out if we do for everytime install deps
#      - name: Fetch Docker image from QEMU
#        uses: docker://registry.gitlab.com/qemu-project/qemu/qemu/ubuntu2004
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install depedencies
        run: bash scripts/qflex/install-deps.sh
      - name: Build and install slirp
        if: contains(matrix.configure-args, 'slirp')
        run: |
          git submodule update --init --recursive slirp 
          git submodule update --remote slirp
          cd slirp 
          meson build 
          sudo ninja -C build install
      - name: Configure
        run: if test -n "$TARGETS"; 
             then
               ./configure --enable-werror --disable-docs $CONFIGURE_ARGS --target-list="$TARGETS" ;
             else
               ./configure --enable-werror --disable-docs $CONFIGURE_ARGS ;
             fi || { cd build && cat config.log meson-logs/meson-log.txt && exit 1; }
      - name: Run meson configure LD_JOBS
        run: if test -n "$LD_JOBS";
             then
               meson configure . -Dbackend_max_links="$LD_JOBS" ;
             fi || exit 1;
      - name: Make base
        run: make -j$(expr $(nproc) + 1)
      - name: Run checks if required
        if: ${{ env.MAKE_CHECK_ARGS }}
        run: make -j$(expr $(nproc) + 1) $MAKE_CHECK_ARGS ;
      - name: Save and upload artifact
        uses: actions/upload-artifact@v2
        with:
          retention-days: 2
          name: ${{ matrix.build-name }}
          path: build

  native_test_job_template:
    runs-on: ubuntu-latest
    name: Runs basic tests for Ubuntu
    needs: native_build_job_definition
    strategy:
      matrix:
        include:
          - make-check-args: check
            build-name: build-system-ubuntu
    env: 
        MAKE_CHECK_ARGS: ${{ matrix.make-check-args }}
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact from build
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.build-name }}
          path: build
      - run: scripts/git-submodule.sh update
             $(sed -n '/GIT_SUBMODULES=/ s/.*=// p' build/config-host.mak)
      - run: find . -type f -exec touch {} +
        working-directory: build
      # Avoid recompiling by hiding ninja with NINJA=":"
      - name: Launch check tests
        run: make NINJA=":" $MAKE_CHECK_ARGS
        working-directory: build
 