name: Build and check tests brought by QEMU

on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  native_build_job_definition:
    runs-on: ubuntu-latest
    name: native_build_job_definition
    description: Builds qemu
    strategy:
      matrix:
        include:
          - build_name: build-system-ubuntu
            targets: aarch64-softmmu
            configure-args: --enable-docs --enable-fdt=system --enable-slirp=system
            make-check-args: check-build
    env: 
      TARGETS: ${{ matrix.targets }}
      CONFIGURE_ARGS: ${{ matrix.configure-args }}
      MAKE_CHECK_ARGS: ${{ inputs.make-check-args }}
    steps:
# Figure out if we do for everytime install deps
#      - name: Fetch Docker image from QEMU
#        uses: docker://registry.gitlab.com/qemu-project/qemu/qemu/ubuntu2004
      - uses: actions/checkout@v2
      - name: Install depedencies
        run: bash scripts/qflex/install-deps.sh
      - run: JOBS=$(expr $(nproc) + 1)
      - run: mkdir build
      - run: cd build
      - name: Configure
        run: if test -n "$TARGETS"; 
             then \
               ../configure --enable-werror --disable-docs $CONFIGURE_ARGS --target-list="$TARGETS" ;
             else \
               ../configure --enable-werror --disable-docs $CONFIGURE_ARGS ;
             fi || { cat config.log meson-logs/meson-log.txt && exit 1; }
      - name: Run meson configure LD_JOBS
        run: if test -n "$LD_JOBS";
             then \
               meson configure . -Dbackend_max_links="$LD_JOBS" ;
             fi || exit 1;
      - name: Make base
        run: make -j"$JOBS"
      - name: Run checks if required
        run: if test -n "$MAKE_CHECK_ARGS";
             then \
               make -j"$JOBS" $MAKE_CHECK_ARGS ;
             fi
      - name: Save and upload artifact
        uses: actions/upload-artifact@v2
        with:
          retention-days: 2
          name: ${{ matrix.build-name }}
          path: build

  native_test_job_template:
    runs-on: ubuntu-latest
    name: Runs basic tests for Ubuntu
    needs: native_build_job_definition
    strategy:
      matrix:
        include:
          make-check-args: check
          build-name: build-system-ubuntu
    env: 
        MAKE_CHECK_ARGS: ${{ matrix.make-check-args }}
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact from build
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.build-name }}
      - run: scripts/git-submodule.sh update
             $(sed -n '/GIT_SUBMODULES=/ s/.*=// p' build/config-host.mak)
      - run: cd build
      - run: find . -type f -exec touch {} +
      # Avoid recompiling by hiding ninja with NINJA=":"
      - name: Launch check tests
        run: make NINJA=":" $MAKE_CHECK_ARGS